swagger: '2.0'
info:
  description: |-
    General data and job management interface. 
     Language specific clients will be generated automatically based on the below specification. Do not write your own http interface to call these APIs.
  version: ${VERSION}
  title: Job System API
host: ${HOST}
basePath: /${BASE_PATH}
tags: []
schemes:
  - http
parameters:
  offsetParam: 
    in: query
    name: offset
    required: false
    type: integer
    minimum: 0
    description: The number of items to skip before starting to collect the result set.
  limitParam:
    in: query
    name: limit
    required: false
    type: integer
    minimum: 1
    maximum: 50
    default: 20
    description: The numbers of items to return.
  queryParam:
    in: query
    name: q
    required: false
    type: string
    description: The stringify json query
  projectParam:
    in: query
    name: p
    required: false
    type: string
    description: The stringify json projection
  sortFieldParam:
    in: query
    name: sort
    required: false
    type: string
    description: The sorting field
  sortOrderParam:
    in: query
    name: order
    required: false
    type: integer
    default: 1
    description: The sorting order where 1 is asc and -1 is desc